name: SCA Check - High Severity - GH Actions 
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk Code Test for High Sev Vulns
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --json | snyk-to-html -o ./results.html|
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with: 
          name: test1
          path: |
